# Generated by Django 4.0.4 on 2022-06-16 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Leaf', '0002_contacto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='tipo_consulta',
            new_name='consulta',
        ),
    ]
