# Generated by Django 4.0.4 on 2022-06-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leaf', '0003_rename_tipo_consulta_contacto_consulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
