# Generated by Django 4.0.4 on 2022-06-17 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Leaf', '0007_remove_producto_cont_cant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productousuario',
            old_name='usuario',
            new_name='user',
        ),
    ]
