# Generated by Django 4.0.4 on 2022-06-17 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Leaf', '0008_rename_usuario_productousuario_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='cantidad',
            new_name='stock',
        ),
    ]
